/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradeInRouteImport } from './routes/trade-in'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as NationwideVehicleDeliveryRouteImport } from './routes/nationwide-vehicle-delivery'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as FordModelsRouteImport } from './routes/ford-models'
import { Route as FinancingRouteImport } from './routes/financing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as AreasWeServeRouteImport } from './routes/areas-we-serve'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as CompareIndexRouteImport } from './routes/compare.index'
import { Route as VehicleIdRouteImport } from './routes/vehicle.$id'
import { Route as GuidesWhatToCheckBeforeBuyingAUsedFordRouteImport } from './routes/guides.what-to-check-before-buying-a-used-ford'
import { Route as GuidesIsFordEcoboostReliableRouteImport } from './routes/guides.is-ford-ecoboost-reliable'
import { Route as GuidesIsAUsedFordF150ReliableRouteImport } from './routes/guides.is-a-used-ford-f-150-reliable'
import { Route as GuidesBestFordSuvForFamiliesRouteImport } from './routes/guides.best-ford-suv-for-families'
import { Route as FordModelRouteImport } from './routes/ford.$model'
import { Route as FordDealerCityRouteImport } from './routes/ford-dealer.$city'
import { Route as FinanceBadCreditRouteImport } from './routes/finance.bad-credit'
import { Route as CompareF150VsF150LightningRouteImport } from './routes/compare.f-150-vs-f-150-lightning'
import { Route as CompareExplorerVsEscapeRouteImport } from './routes/compare.explorer-vs-escape'
import { Route as CompareBroncoVsExplorerRouteImport } from './routes/compare.bronco-vs-explorer'
import { Route as FordDealerCountyCountyRouteImport } from './routes/ford-dealer.county.$county'

const TradeInRoute = TradeInRouteImport.update({
  id: '/trade-in',
  path: '/trade-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const NationwideVehicleDeliveryRoute =
  NationwideVehicleDeliveryRouteImport.update({
    id: '/nationwide-vehicle-delivery',
    path: '/nationwide-vehicle-delivery',
    getParentRoute: () => rootRouteImport,
  } as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FordModelsRoute = FordModelsRouteImport.update({
  id: '/ford-models',
  path: '/ford-models',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingRoute = FinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasWeServeRoute = AreasWeServeRouteImport.update({
  id: '/areas-we-serve',
  path: '/areas-we-serve',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleIdRoute = VehicleIdRouteImport.update({
  id: '/vehicle/$id',
  path: '/vehicle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesWhatToCheckBeforeBuyingAUsedFordRoute =
  GuidesWhatToCheckBeforeBuyingAUsedFordRouteImport.update({
    id: '/guides/what-to-check-before-buying-a-used-ford',
    path: '/guides/what-to-check-before-buying-a-used-ford',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesIsFordEcoboostReliableRoute =
  GuidesIsFordEcoboostReliableRouteImport.update({
    id: '/guides/is-ford-ecoboost-reliable',
    path: '/guides/is-ford-ecoboost-reliable',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesIsAUsedFordF150ReliableRoute =
  GuidesIsAUsedFordF150ReliableRouteImport.update({
    id: '/guides/is-a-used-ford-f-150-reliable',
    path: '/guides/is-a-used-ford-f-150-reliable',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesBestFordSuvForFamiliesRoute =
  GuidesBestFordSuvForFamiliesRouteImport.update({
    id: '/guides/best-ford-suv-for-families',
    path: '/guides/best-ford-suv-for-families',
    getParentRoute: () => rootRouteImport,
  } as any)
const FordModelRoute = FordModelRouteImport.update({
  id: '/ford/$model',
  path: '/ford/$model',
  getParentRoute: () => rootRouteImport,
} as any)
const FordDealerCityRoute = FordDealerCityRouteImport.update({
  id: '/ford-dealer/$city',
  path: '/ford-dealer/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceBadCreditRoute = FinanceBadCreditRouteImport.update({
  id: '/finance/bad-credit',
  path: '/finance/bad-credit',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareF150VsF150LightningRoute =
  CompareF150VsF150LightningRouteImport.update({
    id: '/compare/f-150-vs-f-150-lightning',
    path: '/compare/f-150-vs-f-150-lightning',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareExplorerVsEscapeRoute = CompareExplorerVsEscapeRouteImport.update({
  id: '/compare/explorer-vs-escape',
  path: '/compare/explorer-vs-escape',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareBroncoVsExplorerRoute = CompareBroncoVsExplorerRouteImport.update({
  id: '/compare/bronco-vs-explorer',
  path: '/compare/bronco-vs-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const FordDealerCountyCountyRoute = FordDealerCountyCountyRouteImport.update({
  id: '/ford-dealer/county/$county',
  path: '/ford-dealer/county/$county',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/areas-we-serve': typeof AreasWeServeRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/ford-models': typeof FordModelsRoute
  '/inventory': typeof InventoryRoute
  '/nationwide-vehicle-delivery': typeof NationwideVehicleDeliveryRoute
  '/service': typeof ServiceRoute
  '/trade-in': typeof TradeInRoute
  '/compare/bronco-vs-explorer': typeof CompareBroncoVsExplorerRoute
  '/compare/explorer-vs-escape': typeof CompareExplorerVsEscapeRoute
  '/compare/f-150-vs-f-150-lightning': typeof CompareF150VsF150LightningRoute
  '/finance/bad-credit': typeof FinanceBadCreditRoute
  '/ford-dealer/$city': typeof FordDealerCityRoute
  '/ford/$model': typeof FordModelRoute
  '/guides/best-ford-suv-for-families': typeof GuidesBestFordSuvForFamiliesRoute
  '/guides/is-a-used-ford-f-150-reliable': typeof GuidesIsAUsedFordF150ReliableRoute
  '/guides/is-ford-ecoboost-reliable': typeof GuidesIsFordEcoboostReliableRoute
  '/guides/what-to-check-before-buying-a-used-ford': typeof GuidesWhatToCheckBeforeBuyingAUsedFordRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/compare/': typeof CompareIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/ford-dealer/county/$county': typeof FordDealerCountyCountyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/areas-we-serve': typeof AreasWeServeRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/ford-models': typeof FordModelsRoute
  '/inventory': typeof InventoryRoute
  '/nationwide-vehicle-delivery': typeof NationwideVehicleDeliveryRoute
  '/service': typeof ServiceRoute
  '/trade-in': typeof TradeInRoute
  '/compare/bronco-vs-explorer': typeof CompareBroncoVsExplorerRoute
  '/compare/explorer-vs-escape': typeof CompareExplorerVsEscapeRoute
  '/compare/f-150-vs-f-150-lightning': typeof CompareF150VsF150LightningRoute
  '/finance/bad-credit': typeof FinanceBadCreditRoute
  '/ford-dealer/$city': typeof FordDealerCityRoute
  '/ford/$model': typeof FordModelRoute
  '/guides/best-ford-suv-for-families': typeof GuidesBestFordSuvForFamiliesRoute
  '/guides/is-a-used-ford-f-150-reliable': typeof GuidesIsAUsedFordF150ReliableRoute
  '/guides/is-ford-ecoboost-reliable': typeof GuidesIsFordEcoboostReliableRoute
  '/guides/what-to-check-before-buying-a-used-ford': typeof GuidesWhatToCheckBeforeBuyingAUsedFordRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/compare': typeof CompareIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/ford-dealer/county/$county': typeof FordDealerCountyCountyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/areas-we-serve': typeof AreasWeServeRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/ford-models': typeof FordModelsRoute
  '/inventory': typeof InventoryRoute
  '/nationwide-vehicle-delivery': typeof NationwideVehicleDeliveryRoute
  '/service': typeof ServiceRoute
  '/trade-in': typeof TradeInRoute
  '/compare/bronco-vs-explorer': typeof CompareBroncoVsExplorerRoute
  '/compare/explorer-vs-escape': typeof CompareExplorerVsEscapeRoute
  '/compare/f-150-vs-f-150-lightning': typeof CompareF150VsF150LightningRoute
  '/finance/bad-credit': typeof FinanceBadCreditRoute
  '/ford-dealer/$city': typeof FordDealerCityRoute
  '/ford/$model': typeof FordModelRoute
  '/guides/best-ford-suv-for-families': typeof GuidesBestFordSuvForFamiliesRoute
  '/guides/is-a-used-ford-f-150-reliable': typeof GuidesIsAUsedFordF150ReliableRoute
  '/guides/is-ford-ecoboost-reliable': typeof GuidesIsFordEcoboostReliableRoute
  '/guides/what-to-check-before-buying-a-used-ford': typeof GuidesWhatToCheckBeforeBuyingAUsedFordRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/compare/': typeof CompareIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/ford-dealer/county/$county': typeof FordDealerCountyCountyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/areas-we-serve'
    | '/commercial'
    | '/contact'
    | '/financing'
    | '/ford-models'
    | '/inventory'
    | '/nationwide-vehicle-delivery'
    | '/service'
    | '/trade-in'
    | '/compare/bronco-vs-explorer'
    | '/compare/explorer-vs-escape'
    | '/compare/f-150-vs-f-150-lightning'
    | '/finance/bad-credit'
    | '/ford-dealer/$city'
    | '/ford/$model'
    | '/guides/best-ford-suv-for-families'
    | '/guides/is-a-used-ford-f-150-reliable'
    | '/guides/is-ford-ecoboost-reliable'
    | '/guides/what-to-check-before-buying-a-used-ford'
    | '/vehicle/$id'
    | '/compare/'
    | '/guides/'
    | '/ford-dealer/county/$county'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/areas-we-serve'
    | '/commercial'
    | '/contact'
    | '/financing'
    | '/ford-models'
    | '/inventory'
    | '/nationwide-vehicle-delivery'
    | '/service'
    | '/trade-in'
    | '/compare/bronco-vs-explorer'
    | '/compare/explorer-vs-escape'
    | '/compare/f-150-vs-f-150-lightning'
    | '/finance/bad-credit'
    | '/ford-dealer/$city'
    | '/ford/$model'
    | '/guides/best-ford-suv-for-families'
    | '/guides/is-a-used-ford-f-150-reliable'
    | '/guides/is-ford-ecoboost-reliable'
    | '/guides/what-to-check-before-buying-a-used-ford'
    | '/vehicle/$id'
    | '/compare'
    | '/guides'
    | '/ford-dealer/county/$county'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/areas-we-serve'
    | '/commercial'
    | '/contact'
    | '/financing'
    | '/ford-models'
    | '/inventory'
    | '/nationwide-vehicle-delivery'
    | '/service'
    | '/trade-in'
    | '/compare/bronco-vs-explorer'
    | '/compare/explorer-vs-escape'
    | '/compare/f-150-vs-f-150-lightning'
    | '/finance/bad-credit'
    | '/ford-dealer/$city'
    | '/ford/$model'
    | '/guides/best-ford-suv-for-families'
    | '/guides/is-a-used-ford-f-150-reliable'
    | '/guides/is-ford-ecoboost-reliable'
    | '/guides/what-to-check-before-buying-a-used-ford'
    | '/vehicle/$id'
    | '/compare/'
    | '/guides/'
    | '/ford-dealer/county/$county'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AreasWeServeRoute: typeof AreasWeServeRoute
  CommercialRoute: typeof CommercialRoute
  ContactRoute: typeof ContactRoute
  FinancingRoute: typeof FinancingRoute
  FordModelsRoute: typeof FordModelsRoute
  InventoryRoute: typeof InventoryRoute
  NationwideVehicleDeliveryRoute: typeof NationwideVehicleDeliveryRoute
  ServiceRoute: typeof ServiceRoute
  TradeInRoute: typeof TradeInRoute
  CompareBroncoVsExplorerRoute: typeof CompareBroncoVsExplorerRoute
  CompareExplorerVsEscapeRoute: typeof CompareExplorerVsEscapeRoute
  CompareF150VsF150LightningRoute: typeof CompareF150VsF150LightningRoute
  FinanceBadCreditRoute: typeof FinanceBadCreditRoute
  FordDealerCityRoute: typeof FordDealerCityRoute
  FordModelRoute: typeof FordModelRoute
  GuidesBestFordSuvForFamiliesRoute: typeof GuidesBestFordSuvForFamiliesRoute
  GuidesIsAUsedFordF150ReliableRoute: typeof GuidesIsAUsedFordF150ReliableRoute
  GuidesIsFordEcoboostReliableRoute: typeof GuidesIsFordEcoboostReliableRoute
  GuidesWhatToCheckBeforeBuyingAUsedFordRoute: typeof GuidesWhatToCheckBeforeBuyingAUsedFordRoute
  VehicleIdRoute: typeof VehicleIdRoute
  CompareIndexRoute: typeof CompareIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  FordDealerCountyCountyRoute: typeof FordDealerCountyCountyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trade-in': {
      id: '/trade-in'
      path: '/trade-in'
      fullPath: '/trade-in'
      preLoaderRoute: typeof TradeInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nationwide-vehicle-delivery': {
      id: '/nationwide-vehicle-delivery'
      path: '/nationwide-vehicle-delivery'
      fullPath: '/nationwide-vehicle-delivery'
      preLoaderRoute: typeof NationwideVehicleDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ford-models': {
      id: '/ford-models'
      path: '/ford-models'
      fullPath: '/ford-models'
      preLoaderRoute: typeof FordModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing': {
      id: '/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof FinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-we-serve': {
      id: '/areas-we-serve'
      path: '/areas-we-serve'
      fullPath: '/areas-we-serve'
      preLoaderRoute: typeof AreasWeServeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle/$id': {
      id: '/vehicle/$id'
      path: '/vehicle/$id'
      fullPath: '/vehicle/$id'
      preLoaderRoute: typeof VehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/what-to-check-before-buying-a-used-ford': {
      id: '/guides/what-to-check-before-buying-a-used-ford'
      path: '/guides/what-to-check-before-buying-a-used-ford'
      fullPath: '/guides/what-to-check-before-buying-a-used-ford'
      preLoaderRoute: typeof GuidesWhatToCheckBeforeBuyingAUsedFordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/is-ford-ecoboost-reliable': {
      id: '/guides/is-ford-ecoboost-reliable'
      path: '/guides/is-ford-ecoboost-reliable'
      fullPath: '/guides/is-ford-ecoboost-reliable'
      preLoaderRoute: typeof GuidesIsFordEcoboostReliableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/is-a-used-ford-f-150-reliable': {
      id: '/guides/is-a-used-ford-f-150-reliable'
      path: '/guides/is-a-used-ford-f-150-reliable'
      fullPath: '/guides/is-a-used-ford-f-150-reliable'
      preLoaderRoute: typeof GuidesIsAUsedFordF150ReliableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/best-ford-suv-for-families': {
      id: '/guides/best-ford-suv-for-families'
      path: '/guides/best-ford-suv-for-families'
      fullPath: '/guides/best-ford-suv-for-families'
      preLoaderRoute: typeof GuidesBestFordSuvForFamiliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ford/$model': {
      id: '/ford/$model'
      path: '/ford/$model'
      fullPath: '/ford/$model'
      preLoaderRoute: typeof FordModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ford-dealer/$city': {
      id: '/ford-dealer/$city'
      path: '/ford-dealer/$city'
      fullPath: '/ford-dealer/$city'
      preLoaderRoute: typeof FordDealerCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/bad-credit': {
      id: '/finance/bad-credit'
      path: '/finance/bad-credit'
      fullPath: '/finance/bad-credit'
      preLoaderRoute: typeof FinanceBadCreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/f-150-vs-f-150-lightning': {
      id: '/compare/f-150-vs-f-150-lightning'
      path: '/compare/f-150-vs-f-150-lightning'
      fullPath: '/compare/f-150-vs-f-150-lightning'
      preLoaderRoute: typeof CompareF150VsF150LightningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/explorer-vs-escape': {
      id: '/compare/explorer-vs-escape'
      path: '/compare/explorer-vs-escape'
      fullPath: '/compare/explorer-vs-escape'
      preLoaderRoute: typeof CompareExplorerVsEscapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/bronco-vs-explorer': {
      id: '/compare/bronco-vs-explorer'
      path: '/compare/bronco-vs-explorer'
      fullPath: '/compare/bronco-vs-explorer'
      preLoaderRoute: typeof CompareBroncoVsExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ford-dealer/county/$county': {
      id: '/ford-dealer/county/$county'
      path: '/ford-dealer/county/$county'
      fullPath: '/ford-dealer/county/$county'
      preLoaderRoute: typeof FordDealerCountyCountyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AreasWeServeRoute: AreasWeServeRoute,
  CommercialRoute: CommercialRoute,
  ContactRoute: ContactRoute,
  FinancingRoute: FinancingRoute,
  FordModelsRoute: FordModelsRoute,
  InventoryRoute: InventoryRoute,
  NationwideVehicleDeliveryRoute: NationwideVehicleDeliveryRoute,
  ServiceRoute: ServiceRoute,
  TradeInRoute: TradeInRoute,
  CompareBroncoVsExplorerRoute: CompareBroncoVsExplorerRoute,
  CompareExplorerVsEscapeRoute: CompareExplorerVsEscapeRoute,
  CompareF150VsF150LightningRoute: CompareF150VsF150LightningRoute,
  FinanceBadCreditRoute: FinanceBadCreditRoute,
  FordDealerCityRoute: FordDealerCityRoute,
  FordModelRoute: FordModelRoute,
  GuidesBestFordSuvForFamiliesRoute: GuidesBestFordSuvForFamiliesRoute,
  GuidesIsAUsedFordF150ReliableRoute: GuidesIsAUsedFordF150ReliableRoute,
  GuidesIsFordEcoboostReliableRoute: GuidesIsFordEcoboostReliableRoute,
  GuidesWhatToCheckBeforeBuyingAUsedFordRoute:
    GuidesWhatToCheckBeforeBuyingAUsedFordRoute,
  VehicleIdRoute: VehicleIdRoute,
  CompareIndexRoute: CompareIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  FordDealerCountyCountyRoute: FordDealerCountyCountyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
